### ISSUE TITLE
Modèle Person

### ISSUE THREAD

**Issue by mdevoldere** [3d3d3d-code/ANNU_CSH#1]
Une Personne (Person) est caractérisée par les attributs suivants: **id**, **lastname**, **firstname**, **phone**, **email**, **groupId**.

Déterminer le type de chacun des attributs, modéliser et implémenter la classe "Person".

**Comment by 3d3d3d-code** [comment]
Hi , here the first commit from the team
Could you check my work please , and send me a feedback.
Kind regards
RH
